version: "3"
services:

  scc-state:
    hostname: scc-state
    container_name: scc-state
    build: ./docker/node-clear-linux
    image: node-clear-linux
    labels:
      container_group: scc
    working_dir: /usr/src
    command: node server
    volumes:
      - ./scc-state:/usr/src

  scc-broker-alpha:
    depends_on:
      - scc-state
    hostname: scc-broker-alpha
    container_name: scc-broker-alpha
    build: ./docker/node-clear-linux
    image: node-clear-linux
    labels:
      container_group: scc
    working_dir: /usr/src
    environment:
      - SCC_STATE_SERVER_HOST=scc-state
      - SCC_BROKER_SERVER_PORT=8888
    command: node server
    volumes:
      - ./scc-broker:/usr/src

  scc-broker-beta:
    depends_on:
      - scc-state
    hostname: scc-broker-beta
    container_name: scc-broker-beta
    build: ./docker/node-clear-linux
    image: node-clear-linux
    labels:
      container_group: scc
    working_dir: /usr/src
    environment:
      - SCC_STATE_SERVER_HOST=scc-state
      - SCC_BROKER_SERVER_PORT=8888
    command: node server
    volumes:
      - ./scc-broker:/usr/src

  scc-worker-alpha:
    depends_on:
      - scc-state
      - scc-broker-beta
    hostname: scc-worker-alpha
    container_name: scc-worker-alpha
    build: ./docker/node-clear-linux
    image: node-clear-linux
    labels:
      container_group: scc
    working_dir: /usr/src
    ports:
      - 8000:8000
    environment:
      - SCC_STATE_SERVER_HOST=scc-state
      - SOCKETCLUSTER_PORT=8000
    command: node server
    volumes:
      - ./scc-worker:/usr/src

  scc-worker-beta:
    depends_on:
      - scc-state
      - scc-broker-beta
    hostname: scc-worker-beta
    container_name: scc-worker-beta
    build: ./docker/node-clear-linux
    image: node-clear-linux
    labels:
      container_group: scc
    working_dir: /usr/src
    ports:
      - 8001:8000
    environment:
      - SCC_STATE_SERVER_HOST=scc-state
      - SOCKETCLUSTER_PORT=8000
    command: node server
    volumes:
      - ./scc-worker:/usr/src